### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by oksirets** [oksirets/homepage#4]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by bezdara** [comment]
Skills
archery, sword fighting, killing white walkers, honor and duty, warg

Likes
wilds, direwolves, the Longclaw

Plus
Lord Commander, tame direwolf, cool sword, daddy is hand of the king, brother is king

Minus
bastard, traitor's bastard, nobody knows whose bastard he is, know nothing
