### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by oksirets** [oksirets/homepage#5]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by bezdara** [comment]
In 305 AC
Killed Daenerys Stormborn of the House Targaryen, the First of Her Name, the Unburnt, Queen of Meereen, 
Queen of the Andals and the Rhoynar and the First Men, Khaleesi of the Great Grass Sea, 
Breaker of Chains and Mother of Dragons

In 304 AC
Became King of the North

In 303 AC
Was killed and resurrected

In 303 AC
Became 998 Lord Commander

In 302 AC
Joined the wild

In 300 AC
Fell in love with Ygritte

300 AC - 303 AC
Worked in the night watch

In 283 AC
Born near the end of Robert's Rebellion
